# Generated by Django 5.1.6 on 2025-09-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
