# Generated by Django 5.1.6 on 2025-09-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_profile_pic_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='facebook',
            new_name='linked_in',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='youtube',
        ),
    ]
