# Generated by Django 5.2.5 on 2026-02-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_facebook_customuser_linked_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Economy', 'Economy'), ('Business', 'Business'), ('Sports', 'Sports'), ('Lifestyle', 'Lifestyle')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
